name: credential-store-pipeline

on: push

jobs:
  build-go:
    env:
      GOOS: linux
      GOARCH: amd64
    name: build Go backend
    steps:
      run: |
        cd src/loginService
        go build
  
  cdk-synth:
    name: AWS CDK Synth
    needs: build-go
  
  test:
    name: test

  cdk-deploy:
    name: AWS CDK Deploy
    needs: [cdk-synth, test]
  
