name: credential-store-pipeline

on: push
  

jobs:
  build-go:
    name: build Go backend
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - uses: actions/checkout@main
        with: 
          ref: ${{ github.ref }}
      - name: Building Go login service
        run: GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o ./build/bootstrap ./src/loginService/loginService.go
      - run: ls ./build
      
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Running unit tests
        run: |
          npm ci
  
  cdk-synth:
    name: AWS CDK Synth
    needs: [build-go, unit-test]
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::339712770705:role/credential-store-cicd-role
          
      - uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Synthesizing AWS Infrastructure
        run: |
          cdk synth
          cdk diff

  cdk-deploy:
    name: AWS CDK Deploy
    if: github.ref == 'refs/heads/main'
    needs: cdk-synth
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
    steps:
      - uses: actions/checkout@main
      - name: Deploying AWS Infrastructure
        run: |
          cdk diff
          cdk deploy
  
